site_name: ROADIES

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - toc.follow
    - toc.integrate
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: custom
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: custom
      accent: lime
    
  favicon: images/ROADIES_logo.png
  logo: images/ROADIES_logo.png

plugins:
  - social
  - search

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/TurakhiaLab

nav:
  - Home: index.md
  - Install: install.md
  - Quick Start: quickstart.md
  - User Guide: usage.md
  - Contribution: contribution.md
  - Troubleshooting: troubleshooting.md
  - Cite ROADIES: cite.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

repo_url: https://github.com/TurakhiaLab/ROADIES

repo_name: TurakhiaLab/ROADIES

copyright: |
  &copy; 2024 <a href="https://github.com/TurakhiaLab"  target="_blank" rel="noopener">Turakhia Lab</a>
