#This file configures the parameters for ROADIES

#Path for input genomes
GENOMES: "/home/roadies-datasets/gzipped_flies_renamed"
#Reference tree (optional, default set as null)
REFERENCE: reference_trees/flies_reftree_100.nwk
#Length of each of the genes
LENGTH: 500
#Number of genes per iteration
GENE_COUNT: 50
#Minimum % uppercase for sampling valid genes
UPPER_CASE: 0.90
#ROADIES output directory
OUT_DIR: "results"
#Minimum number of species in a gene fasta (4 min for ASTRAL-Pro)
MIN_ALIGN: 4 
#Minimum % match in LASTZ alignment
IDENTITY: 65
#Minimum input sequence coverage in LASTZ alignment
COVERAGE: 85
#Minimum continuity of LASTZ alignments
CONTINUITY: 85
#Max number of gene copies from a genome in an alignment
MAX_DUP: 10
#Mumber of steps in LASTZ sampling
STEPS: 1
#PASTA filtering parameters
FILTERFRAGMENTS: 0.50
MASKSITES: 0.02
#Number of iterations (for --converge option)
ITERATIONS: 3