#This file configures the parameters for ROADIES and converge
#Path for input genomes

GENOMES: "/datasets/gzipped_birds_new"
#reference tree for converge (used for ref_dist.csv)
REFERENCE: "trees/birds_reftree_363_latest.nwk"
#length of genes
LENGTH: 500
#number of genes
GENE_MULT: 2
#minimum % uppercase for genes
UPPER_CASE: 0.90
#ROADIES output directory
OUT_DIR: "results"
#minimum number of species in a gene fasta (4 min for ASTRAL-PRO)
MIN_ALIGN: 4 
#minimum % match in alignment
IDENTITY: 65
#minimum input sequence coverage
COVERAGE: 85
#minimum continuity of alignments
CONTINUITY: 85
#max number of copies from a genome in an alignment
MAX_DUP: 10
#number of steps in lastz sampling (increasing number speeds up alignment but decreases lastz accuracy)
STEPS: 1
#number of bootstrapped trees for comparison
NUM_BOOTSTRAP: 10
#input ROADIES gene trees for converge
INPUT_GENE_TREES: null
#input ROADIES mapping file for converge
INPUT_MAP: null
#min converge runs before stopping
MIN_ITER: 5
#max runtime in hours
MAX_RUNTIME: 72
#percentage of genes that use weighted sampling
WEIGHTED: 0.3
#percentage of species to align during lastz with weighted sampling
TO_ALIGN: 100
FILTERFRAGMENTS: 0.50
MASKSITES: 0.02
#add modes
MSA: "mashtree" #"fasttree", "mashtree"