#This file configures the parameters for ROADIES and converge
#Path for input genomes

GENOMES: "/home/roadies-datasets/gzipped_flies_renamed"
#reference tree for converge (used for ref_dist.csv)
REFERENCE: trees/flies_reftree_100.nwk
#length of genes
LENGTH: 500
#number of genes
GENE_COUNT: 10000
#minimum % uppercase for genes
UPPER_CASE: 0.90
#ROADIES output directory
OUT_DIR: "results"
#minimum number of species in a gene fasta (4 min for ASTRAL-PRO)
MIN_ALIGN: 4 
#minimum % match in alignment
IDENTITY: 65
#minimum input sequence coverage
COVERAGE: 85
#minimum continuity of alignments
CONTINUITY: 85
#max number of copies from a genome in an alignment
MAX_DUP: 10
#number of steps in lastz sampling (increasing number speeds up alignment but decreases lastz accuracy)
STEPS: 1
#pasta parameters
FILTERFRAGMENTS: 0.50
MASKSITES: 0.02