name: ci

on:
  push:
    branches:
      - master
      - main
      - final-cleanup
      - rename-repo-astral

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      
      - name: Download and Unzip Genomes
        run: |
          mkdir -p test/test_data
          while read link; do
            wget -P test/test_data "$link"
            zip_file=$(basename "$link")
            unzip -d test/test_data "test/test_data/$zip_file"
          done < test/input_genome_links.txt

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          channels: conda-forge, bioconda
          activate-environment: roadies_env_test
          environment-file: test/roadies_env_test.yaml

      - name: Run Tests
        shell: bash -l {0}
        run: |
          chmod +x test/roadies_env_test.sh
          source test/roadies_env_test.sh
          pip3 install ete3 six numpy PyYAML
          python run_roadies.py --cores 32 --config test/test_config.yaml --mode accurate

      - name: Install dependencies for mkdocs
        run: |
          pip install mkdocs-material
          pip install "mkdocs-material[imaging]"

      - run: mkdocs gh-deploy --force
